### ISSUE TITLE
Potential output overflow, gcc complaint

### ISSUE THREAD

**Issue by cmsigler** [qemacs/qemacs#12]
Hi,

Building r1185 there is a potential output overflow in extras.c.  Complaint from gcc 12.2.0:

CC -c extras.c
extras.c: In function ‘charname_complete’:
extras.c:1980:55: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 1980 |                 snprintf(entry, sizeof entry, "%s\t%5s", p1, buf);
      |                                                       ^
In file included from /usr/include/stdio.h:906,
                 from qe.h:30,
                 from extras.c:23:
In function ‘snprintf’,
    inlined from ‘charname_complete’ at extras.c:1980:17:
/usr/include/bits/stdio2.h:54:10: note: ‘__builtin___snprintf_chk’ output 7 or more bytes (assuming 257) into a destination of size 256
   54 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~
extras.c: In function ‘charname_complete’:
extras.c:1964:55: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 1964 |                 snprintf(entry, sizeof entry, "%s\t%5s", p1, buf);
      |                                                       ^
In function ‘snprintf’,
    inlined from ‘charname_complete’ at extras.c:1964:17:
/usr/include/bits/stdio2.h:54:10: note: ‘__builtin___snprintf_chk’ output 7 or more bytes (assuming 257) into a destination of size 256
   54 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~

Didn't see this complaint building r1182.  Based on a prior fix you made, commit 490ebfb, maybe the sizes of the arrays need adjusting.  HTH :)

Clemmitt Sigler

**Comment by cmsigler** [comment]
Hi,

I hope this suggested patch helps:

==== CUT HERE ====

    --- extras.c.orig	2022-11-09 13:21:28.981011381 -0500
    +++ extras.c	2022-11-09 13:40:46.571628561 -0500
    @@ -1942,7 +1942,7 @@
     
     static void charname_complete(CompleteState *cp, CompleteFunc enumerate) {
         char buf[256];
    -    char entry[256];
    +    char entry[272];
         FILE *fp;
     
         /* enumerate Unicode character names from Unicode consortium data */

==== CUT HERE ====

With this, the (harmless) warnings are eliminated.  HTH :-)

Clemmitt Sigler

**Comment by chqrlie** [comment]
Hello,

This is not per se a bug, rather a warning about potential string truncation by `snprintf`, which is not a problem given the context.
The warning should nevertheless be silenced.
I am going to increase the size of the `entry` array and specify a maximum size for the hex encoding with `%5.6s` to fix this issue.
My compiler versions do not produce this warning, I shall set up a server with a more recent version of gcc to avoid committing patches 
with such problems in the future.

Best regards

Chqrlie.

**Comment by cmsigler** [comment]
@chqrlie ,

As always, thank you for all your hard work and help :-D

Clemmitt

**Comment by chqrlie** [comment]
This was fixed in commit 138be0a3ca79808bfff5eb43574a03beead09468 by increasing the target buffer length.
