### ISSUE TITLE
configure does not detect ARM CPU on Linux

### ISSUE THREAD

**Issue by posguy99** [qemacs/qemacs#19]
Tested on both Fedora and Kali Linux.

```
$ ./configure
VERSION             6.1.1c
Install prefix      /usr/local
Shared data dir     /usr/local/share
Manpages dir        /usr/local/man
Source path         /home/parallels/src/qemacs
C compiler          gcc
  version           gcc (Debian 13.2.0-13) 13.2.0
  target_arch       unknown
Tiny build          no
X11 support         no
libpng support      no
FFMPEG support      no
Graphical HTML      no
Memory mapped files yes
Unlocked I/O        yes
Plugins support     yes
Bidir support       yes
All kmaps           yes
All modes           yes
Build doc files     no

Creating config.mak and config.h
config.mak is unchanged
config.h is unchanged
```

This is because the configure script only checks `uname -m` for 'arm', so it works on a Mac, but does not test for 'aarch64', so the result is 'unknown'

```
$ uname -m
aarch64
```

**Comment by chqrlie** [comment]
So you are running linux in a vm on a mac with an M1 or an M2 chip?
I shall fix this quickly

**Comment by posguy99** [comment]
My test machine is an M2Max.  It still builds, so the compiler is probably doing "the right thing".

**Comment by posguy99** [comment]
It looks like https://github.com/qemacs/qemacs/commit/ea6a70963e12adfbf02a297228eac3ceaef3283e fixes this issue.
