### ISSUE TITLE
Feature request: 'q' to quit dired mode

### ISSUE THREAD

**Issue by Piscium** [qemacs/qemacs#2]
In Emacs, if I press 'C-x d' to go into dired mode, and then 'q', I go back to the buffer where I was before going into dired mode, and out of dired mode (in for example, fundamental mode). More details at the bottom of this page:

https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired-Enter.html

This a request to implement the same feature in Qemacs. Currently if I press 'q' I get 'Buffer is read only'.

Since Qemacs starts in dired mode if no file is passed as parameter when it starts, the natural thing would be for Qemacs to go to  scratch buffer if 'q' is pressed.

**Comment by Piscium** [comment]
Hi Charlie,

With the change you made 'q' does the same as 'C-g', it was bound in addition to it.  However both in mg and emacs, if I press 'C-x d RET' to go into dired mode and open a folder, and then press 'q', I am back in the buffer where I previously was. This is what I had asked for. In the case of calling qemacs without passing a file name this would mean the scratch buffer would be shown.
It looks like you don't think it is a good idea. :-)

**Comment by chqrlie** [comment]
Hi Piscium,

I do believe it is a good idea, I just posted a quick fix for now.

Cheers

Chqrlie.

**Comment by Piscium** [comment]
Thanks. I took a quick look at mg, like in emacs q is bound to a function called  "quit-window".

d_killbuffer_cmd,	/* q */
funmap_add(d_killbuffer_cmd, "quit-window", 0);
