### ISSUE TITLE
[question] windows resize in qe (tty version)

### ISSUE THREAD

**Issue by antoniocorbi** [qemacs/qemacs#21]
Hi,

New to qe here!

When using "qe" (the tty executable, not "xqe") and  once a window is created via "C-x 2", "C-x  3"... is it possible to resize it like in xqe or in plain emacs?

Thx!

**Comment by chqrlie** [comment]
Hi @antoniocorbi 

There is no current command to do this.  You can split the window with different proportions using a numeric prefix to `C-x 2` and `C-x 3`.

I shall add the following commands to make this easier in the next version:
- `enlarge-window` on `C-x ^`
- `enlarge-window-horizontally` on `C-x }`
- `shrink-window` on `C-x &`
- `shrink-window-horizontally` on `C-x {`
- `resize-window` on `C-x +` (interactive resizing using `up`, `down`, `left` and `right`.)

**Comment by antoniocorbi** [comment]
Hi @chqrlie ,

Thanks for the answer and the tip!

**Comment by chqrlie** [comment]
@antoniocorbi  I committed the functions described here above, tell me if the behavior is what you would expect. `C-x +` is quite effective IMHO.

**Comment by antoniocorbi** [comment]
Hi @chqrlie ,
Thx for implementing this so quickly!
It works as expected.
Compared to standard emacs I only miss repetition.

**Comment by antoniocorbi** [comment]
In standard emacs I only would press one time C-x and then each press alone of '^' or 'v' would expand/contract the window instead of having to press "C-x ^" or "C-x v" each time.

**Comment by chqrlie** [comment]
> In standard emacs I only would press one time C-x and then each press in a row alone of '^' or 'v' would expand/contract the window instead of having to press "C-x ^" or "C-x v" each time.

This does not work in my version (`emacs-version` shows `GNU Emacs 29.3 (build 1, aarch64-apple-darwin23.4.0) of 2024-03-24`)

**Comment by antoniocorbi** [comment]
Hi @chqrlie ,
I think you have to toggle on repeat-mode, after that you can do things as described here[1].
It's very practical for me as it requires less key presses for repeating an action.

[1] https://www.gnu.org/software/emacs/manual/html_node/emacs/Repeating.html

**Comment by chqrlie** [comment]
> Hi @chqrlie , I think you have to toggle on repeat-mode, after that you can do things as described here[1]. It's very practical for me as it requires less key presses for repeating an action.
> 
> [1] https://www.gnu.org/software/emacs/manual/html_node/emacs/Repeating.html

Very interesting, I was not aware of `repeat-mode` (beyond the universal argument repeat prefix, which is supported in QEmacs).  I shall investigate an elegant and efficient way to implement this *transient repeat mode*.

**Comment by antoniocorbi** [comment]
I learnt about repeat-mode not so long ago and since then it's been in my emacs-muscle-memory.
That's why (after you implemented window resize) I instintively tried repetition :)

Thanks for your work in qemacs!

**Comment by chqrlie** [comment]
@antoniocorbi   I implemented `repeat` and `repeat-mode`, which is always enabled.  Check out this PR: #34.
Tell me if your muscle memory feels at home :)

**Comment by antoniocorbi** [comment]
> @antoniocorbi I implemented `repeat` and `repeat-mode`, which is always enabled. Check out this PR: #34. Tell me if your muscle memory feels at home :)

Sweeeeeet   ;)

Thanks @chqrlie !
