### ISSUE TITLE
C-x C-l does not work

### ISSUE THREAD

**Issue by Piscium** [qemacs/qemacs#6]
C-x C-l is supposed to convert a region to lowercase, in Emacs and Qemacs (see qeconfig.h, line 250), instead it wants to do a comparison. C-x C-u converts to upper case as expected.

Tested with the current version, commit 0b61bbb0c5c938dadb7d6440955a80a44058c9e7.

**Comment by qemacs** [comment]
Hello Piscium

Thank you for your feedback.
I changed the default binding for compare-files, thus fixing this issue

Best regards

Chqrlie
